name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

permissions:
  packages: write

jobs:

  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: '1'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      # PackageOutputPath: '${{ github.workspace }}\package'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #   fetch-depth: 0

    - name: Build & Test
      uses: unitycontainer/.github/.github/workflows/build-test-flow.yml@main
      with:
        checkout-path: ''
        PackageOutputPath: '${{ github.workspace }}\package'
      secrets: inherit

    # call-workflow-passing-data:

    # - name: Publish Local Package
    #   run: |
    #     dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
    #     dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github

    # - name: Label Fixed Issues
    #   uses: gh-bot/fix-labeler@master        
