name:  Continuous Deployment

on:
  push:
    # branches:
    #   - 'release/**'    
    #   - 'prototype/**'    
 
jobs: 

  call-build-package-flow:
    uses: unitycontainer/.github/.github/workflows/build-package-flow.yml@main
    with:
      artifact-name: 'experimental'
    secrets: inherit 

  call-continuous-deployment-flow:
    uses: unitycontainer/.github/.github/workflows/continuous-deployment-flow.yml@main
    with:
      artifact-name: 'experimental'
    secrets: inherit
