name:  Continuous Deployment

on:
  push:
    # branches:
    #   - 'release/**'    
    #   - 'prototype/**'    
 
jobs: 

  call-build-package-flow:
    uses: unitycontainer/.github/.github/workflows/build-package-flow.yml@main
    with:
      artifact-name: 'experimental'
    secrets: inherit 

  call-publish-artifact-flow:
    needs: [ call-build-package-flow ]
    # if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    uses: unitycontainer/.github/.github/workflows/publish-artifact-flow.yml@main
    with:
      artifact-name: 'experimental'
    secrets: inherit
