name: Build Source

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Tags
      run: git fetch --unshallow 

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore
      run: nuget restore src\Unity.Experimental.csproj

    - name: Build
      run: msbuild src\Unity.Experimental.csproj /t:Build /p:Configuration=Release -v:m

